// Generated by the WebObjects Assistant Mon Oct 15 16:36:28 Asia/Calcutta 2001

import webobjectsexamples.businesslogic.movies.common.Movie;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WODisplayGroup;

public class Main extends WOComponent {

    protected Movie movie;
    // This WODisplayGroup is initialized from the .woo archive in the component's constructor method
    protected WODisplayGroup movieDisplayGroup;

    public Main(WOContext context) {
        super(context);
    }


}
